<?php

namespace Database\Seeders;

use App\Models\Subject;
use Illuminate\Database\Seeder;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;

class Subjects extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $subjects = [
            [
                'degree_programme_id' => 1,
                'subject_code' => 'IT 175',
                'name' => 'Introduction to Graphics Tools',
                'description' => 'Basic graphics tools and techniques.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'degree_programme_id' => 1,
                'subject_code' => 'IT 180',
                'name' => 'Introduction to Computing',
                'description' => 'Fundamentals of computing.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'degree_programme_id' => 1,
                'subject_code' => 'IT 181',
                'name' => 'Mathematics for Computing I',
                'description' => 'Basic math concepts in computing.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'degree_programme_id' => 1,
                'subject_code' => 'IT 182',
                'name' => 'Programming Methodologies',
                'description' => 'Core programming principles.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'degree_programme_id' => 1,
                'subject_code' => 'IT 184',
                'name' => 'Database Management Systems I',
                'description' => 'Introduction to databases.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'degree_programme_id' => 1,
                'subject_code' => 'IT 185',
                'name' => 'Client-Side Web Technologies',
                'description' => 'Client-side web tools and techniques.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'degree_programme_id' => 1,
                'subject_code' => 'IT 137',
                'name' => 'English & Communication I',
                'description' => 'Communication basics in English.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'degree_programme_id' => 1,
                'subject_code' => 'IT 186',
                'name' => 'Human-Computer Interaction',
                'description' => 'Introduction to HCI concepts.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'degree_programme_id' => 1,
                'subject_code' => 'IT 187',
                'name' => 'System Analysis and Design',
                'description' => 'Principles of system design.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'degree_programme_id' => 1,
                'subject_code' => 'IT 196',
                'name' => 'Basic Probability and Statistics',
                'description' => 'Fundamentals of probability and stats.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'degree_programme_id' => 1,
                'subject_code' => 'IT 197',
                'name' => 'Server-Side Web Development',
                'description' => 'Server-side web development skills.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'degree_programme_id' => 1,
                'subject_code' => 'IT 235',
                'name' => 'Introduction to Object-Oriented Programming Concepts',
                'description' => 'Core OOP principles.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'degree_programme_id' => 1,
                'subject_code' => 'IT 138',
                'name' => 'English & Communication II',
                'description' => 'Advanced English communication.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'degree_programme_id' => 1,
                'subject_code' => 'IT 130',
                'name' => 'Soft Skills and Service Project',
                'description' => 'Developing soft skills.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'degree_programme_id' => 1,
                'subject_code' => 'IT 131',
                'name' => 'Meditation',
                'description' => 'Practice of meditation techniques.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'degree_programme_id' => 1,
                'subject_code' => 'IT 183',
                'name' => 'Computer Architecture',
                'description' => 'Basics of computer architecture.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'degree_programme_id' => 1,
                'subject_code' => 'IT 198',
                'name' => 'Project Work',
                'description' => 'Hands-on project experience.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'degree_programme_id' => 1,
                'subject_code' => 'IT 236',
                'name' => 'Database Management Systems II',
                'description' => 'Advanced DBMS concepts.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'degree_programme_id' => 1,
                'subject_code' => 'IT 237',
                'name' => 'Computer Networks and Data Communication',
                'description' => 'Foundations of networking.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'degree_programme_id' => 1,
                'subject_code' => 'IT 239',
                'name' => 'Mathematics for Computing II',
                'description' => 'Advanced math in computing.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'degree_programme_id' => 1,
                'subject_code' => 'IT 241',
                'name' => 'Software Engineering',
                'description' => 'Software engineering principles.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'degree_programme_id' => 1,
                'subject_code' => 'IT 139',
                'name' => 'English & Communication III',
                'description' => 'Continued English communication.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'degree_programme_id' => 1,
                'subject_code' => 'IT 188',
                'name' => 'Computer Graphics',
                'description' => 'Fundamentals of computer graphics.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'degree_programme_id' => 1,
                'subject_code' => 'IT 240',
                'name' => 'Advanced Programming with Java I',
                'description' => 'Java programming skills.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'degree_programme_id' => 1,
                'subject_code' => 'IT 242',
                'name' => 'Data Structures and Algorithms',
                'description' => 'Foundations of data structures.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'degree_programme_id' => 1,
                'subject_code' => 'IT 244',
                'name' => 'Operating Systems Concepts',
                'description' => 'Basics of operating systems.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'degree_programme_id' => 1,
                'subject_code' => 'IT 245',
                'name' => 'Network Design and Administration',
                'description' => 'Designing and managing networks.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'degree_programme_id' => 1,
                'subject_code' => 'IT 140',
                'name' => 'English & Communication IV',
                'description' => 'Enhanced communication skills.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'degree_programme_id' => 1,
                'subject_code' => 'IT 243',
                'name' => 'IT Project Management',
                'description' => 'Principles of project management.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'degree_programme_id' => 1,
                'subject_code' => 'IT 250',
                'name' => 'Advanced Database Systems',
                'description' => 'Advanced database concepts.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'degree_programme_id' => 1,
                'subject_code' => 'IT 253',
                'name' => 'System Administration with Linux',
                'description' => 'Linux system administration.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'degree_programme_id' => 1,
                'subject_code' => 'IT 256',
                'name' => 'Data Science and Analytics',
                'description' => 'Basics of data science.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'degree_programme_id' => 1,
                'subject_code' => 'IT 141',
                'name' => 'English & Communication V',
                'description' => 'Professional communication.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'degree_programme_id' => 1,
                'subject_code' => 'IT 189',
                'name' => 'Advanced Topics in Information Technology',
                'description' => 'Advanced IT concepts.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'degree_programme_id' => 1,
                'subject_code' => 'IT 249',
                'name' => 'Software Quality Assurance',
                'description' => 'Ensuring software quality.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'degree_programme_id' => 1,
                'subject_code' => 'IT 251',
                'name' => 'Advanced Web Development',
                'description' => 'Advanced web development skills.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'degree_programme_id' => 1,
                'subject_code' => 'IT 252',
                'name' => 'Information Security',
                'description' => 'Introduction to cybersecurity.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'degree_programme_id' => 1,
                'subject_code' => 'IT 255',
                'name' => 'Advanced Programming with Java II',
                'description' => 'Advanced Java techniques.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'degree_programme_id' => 1,
                'subject_code' => 'IT 238',
                'name' => 'Ethical and Legal Aspects in IT',
                'description' => 'Ethics in IT industry.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'degree_programme_id' => 1,
                'subject_code' => 'IT 246',
                'name' => 'Cloud Computing',
                'description' => 'Fundamentals of cloud technology.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'degree_programme_id' => 1,
                'subject_code' => 'IT 254',
                'name' => 'Digital Image Processing',
                'description' => 'Basics of image processing.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'degree_programme_id' => 1,
                'subject_code' => 'IT 257',
                'name' => 'Bioinformatics',
                'description' => 'Introduction to bioinformatics.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'degree_programme_id' => 1,
                'subject_code' => 'IT 345',
                'name' => 'Artificial Intelligence',
                'description' => 'Introduction to AI concepts.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'degree_programme_id' => 1,
                'subject_code' => 'IT 368',
                'name' => 'Proposal Presentation',
                'description' => 'Presenting research proposals.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'degree_programme_id' => 1,
                'subject_code' => 'IT 344',
                'name' => 'Android Development',
                'description' => 'Basics of Android programming.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'degree_programme_id' => 1,
                'subject_code' => 'IT 367',
                'name' => 'Project Work and Report Writing',
                'description' => 'Project work and documentation.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'degree_programme_id' => 1,
                'subject_code' => 'IT 380',
                'name' => 'Internship',
                'description' => 'Practical industry experience.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'degree_programme_id' => 3,
                'subject_code' => 'MGT 165',
                'name' => 'Principles of Management',
                'description' => 'Fundamental management concepts.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'degree_programme_id' => 3,
                'subject_code' => 'MGT 166',
                'name' => 'Marketing Management',
                'description' => 'Basics of marketing principles.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'degree_programme_id' => 3,
                'subject_code' => 'MGT 167',
                'name' => 'Organizational Leadership',
                'description' => 'Leadership principles in organizations.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'degree_programme_id' => 3,
                'subject_code' => 'MGT 168',
                'name' => 'Industrial Law and Industrial Relations',
                'description' => 'Basics of industrial law and relations.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'degree_programme_id' => 3,
                'subject_code' => 'MGT 344',
                'name' => 'Exposure Visit I',
                'description' => 'Industry exposure experience.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'degree_programme_id' => 3,
                'subject_code' => 'MGT 169',
                'name' => 'Introduction to Financial Accounting',
                'description' => 'Fundamentals of financial accounting.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'degree_programme_id' => 3,
                'subject_code' => 'MGT 170',
                'name' => 'Organizational Behavior',
                'description' => 'Study of behavior within organizations.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'degree_programme_id' => 3,
                'subject_code' => 'MGT 171',
                'name' => 'Entrepreneurship',
                'description' => 'Essentials of starting a business.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'degree_programme_id' => 3,
                'subject_code' => 'MGT 173',
                'name' => 'Operations Management',
                'description' => 'Introduction to managing operations.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'degree_programme_id' => 3,
                'subject_code' => 'MGT 174',
                'name' => 'Project Management',
                'description' => 'Basics of managing projects.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'degree_programme_id' => 3,
                'subject_code' => 'MGT 175',
                'name' => 'Human Resource Management',
                'description' => 'Principles of managing human resources.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'degree_programme_id' => 3,
                'subject_code' => 'MGT 177',
                'name' => 'Strategic Management',
                'description' => 'Strategies for business success.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'degree_programme_id' => 3,
                'subject_code' => 'MGT 178',
                'name' => 'Career Development',
                'description' => 'Skills for professional growth.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'degree_programme_id' => 3,
                'subject_code' => 'MGT 345',
                'name' => 'Project Work',
                'description' => 'Capstone project experience.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'degree_programme_id' => 3,
                'subject_code' => 'MGT 344',
                'name' => 'Exposure Visit II',
                'description' => 'Advanced industry exposure.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'degree_programme_id' => 4,
                'subject_code' => 'MGT 111803',
                'name' => 'Principles of Management',
                'description' => 'Fundamental management concepts.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'degree_programme_id' => 4,
                'subject_code' => 'MGT 111814',
                'name' => 'Financial Accounting',
                'description' => 'Introductory financial accounting.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'degree_programme_id' => 4,
                'subject_code' => 'MGT 111832',
                'name' => 'Information Technology',
                'description' => 'IT basics for management.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'degree_programme_id' => 4,
                'subject_code' => 'MGT 111442',
                'name' => 'Business Communication - I',
                'description' => 'Communication skills for business.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'degree_programme_id' => 4,
                'subject_code' => 'MGT 111331',
                'name' => 'Practical Mindfulness Meditation I',
                'description' => 'Mindfulness practice basics.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'degree_programme_id' => 4,
                'subject_code' => 'MGT 111271',
                'name' => 'Practical Yoga Meditation I',
                'description' => 'Intro to yoga meditation.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'degree_programme_id' => 4,
                'subject_code' => 'SPD 101',
                'name' => 'Students Professional Development I',
                'description' => 'Career development activities.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'degree_programme_id' => 4,
                'subject_code' => 'SOS 112',
                'name' => 'Counselling Psychology and its Practice I',
                'description' => 'Intro to counselling techniques.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'degree_programme_id' => 4,
                'subject_code' => 'MGT 111823',
                'name' => 'Business Mathematics',
                'description' => 'Mathematics in business applications.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'degree_programme_id' => 4,
                'subject_code' => 'MGT 121843',
                'name' => 'Microeconomics',
                'description' => 'Basics of microeconomics.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'degree_programme_id' => 4,
                'subject_code' => 'MGT 121863',
                'name' => 'Cost and Management Accounting',
                'description' => 'Principles of cost accounting.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'degree_programme_id' => 4,
                'subject_code' => 'MGT 121452',
                'name' => 'Business Communication – II',
                'description' => 'Advanced communication in business.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'degree_programme_id' => 4,
                'subject_code' => 'MGT 121341',
                'name' => 'Practical Mindfulness Meditation II',
                'description' => 'Mindfulness techniques level II.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'degree_programme_id' => 4,
                'subject_code' => 'MGT 121281',
                'name' => 'Practical Yoga Meditation II',
                'description' => 'Advanced yoga meditation.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'degree_programme_id' => 4,
                'subject_code' => 'SPD 102',
                'name' => 'Students Professional Development II',
                'description' => 'Career skills enhancement.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'degree_programme_id' => 4,
                'subject_code' => 'SOS 122',
                'name' => 'Counselling Psychology and its Practice II',
                'description' => 'Counselling skills continuation.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'degree_programme_id' => 4,
                'subject_code' => 'MGT 121853',
                'name' => 'Marketing Management',
                'description' => 'Essentials of marketing management.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'degree_programme_id' => 4,
                'subject_code' => 'MGT 121873',
                'name' => 'Business Statistics',
                'description' => 'Statistics in business decisions.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'degree_programme_id' => 4,
                'subject_code' => 'MGT 211883',
                'name' => 'Macroeconomics',
                'description' => 'Macroeconomic principles.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'degree_programme_id' => 4,
                'subject_code' => 'MGT 131462',
                'name' => 'Business Communication – III',
                'description' => 'Effective communication strategies.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'degree_programme_id' => 4,
                'subject_code' => 'MGT 211351',
                'name' => 'Practical Mindfulness Meditation III',
                'description' => 'Advanced mindfulness practices.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'degree_programme_id' => 4,
                'subject_code' => 'MGT 211291',
                'name' => 'Practical Yoga Meditation III',
                'description' => 'Level III yoga meditation.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'degree_programme_id' => 4,
                'subject_code' => 'SPD 201',
                'name' => 'Students Professional Development III',
                'description' => 'Enhanced career readiness.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'degree_programme_id' => 4,
                'subject_code' => 'SOS 132',
                'name' => 'Counselling Psychology and its Practice III',
                'description' => 'Further counselling practices.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'degree_programme_id' => 4,
                'subject_code' => 'MGT 211894',
                'name' => 'Advanced Financial Accounting',
                'description' => 'Advanced topics in accounting.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'degree_programme_id' => 4,
                'subject_code' => 'MGT 211903',
                'name' => 'Human Resource Management',
                'description' => 'Fundamentals of HR management.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'degree_programme_id' => 4,
                'subject_code' => 'MGT 211913',
                'name' => 'Business Law',
                'description' => 'Introduction to business law.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'degree_programme_id' => 4,
                'subject_code' => 'MGT 213421',
                'name' => 'Industrial Visit - I',
                'description' => 'Industry visit for exposure.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'degree_programme_id' => 4,
                'subject_code' => 'MGT 211472',
                'name' => 'Business Communication – IV',
                'description' => 'Communication in business context.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'degree_programme_id' => 4,
                'subject_code' => 'SPD 202',
                'name' => 'Students Professional Development IV',
                'description' => 'Career readiness activities.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'degree_programme_id' => 4,
                'subject_code' => 'SOS 142',
                'name' => 'Counselling Psychology and its Practice IV',
                'description' => 'Advanced counselling techniques.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'degree_programme_id' => 2,
                'name' => 'Introduction to Computing',
                'description' => 'Fundamentals of computing concepts.',
                'created_at' => now(),
                'updated_at' => now(),
                'subject_code' => '000',
            ],
            [
                'degree_programme_id' => 2,
                'name' => 'Mathematics for Computing I',
                'description' => 'Mathematics fundamentals for computing.',
                'created_at' => now(),
                'updated_at' => now(),
                'subject_code' => '000',
            ],
            [
                'degree_programme_id' => 2,
                'name' => 'Programming Methodologies',
                'description' => 'Techniques for effective programming.',
                'created_at' => now(),
                'updated_at' => now(),
                'subject_code' => '000',
            ],
            [
                'degree_programme_id' => 2,
                'name' => 'Client Side Web Technologies',
                'description' => 'Web technologies for client-side development.',
                'created_at' => now(),
                'updated_at' => now(),
                'subject_code' => '000',
            ],
            [
                'degree_programme_id' => 2,
                'name' => 'Introduction to Graphic Tools',
                'description' => 'Basics of graphic design tools.',
                'created_at' => now(),
                'updated_at' => now(),
                'subject_code' => '000',
            ],
            [
                'degree_programme_id' => 2,
                'name' => 'Computer Architecture',
                'description' => 'Overview of computer architecture.',
                'created_at' => now(),
                'updated_at' => now(),
                'subject_code' => '000',
            ],
            [
                'degree_programme_id' => 2,
                'name' => 'Advanced English Grammar & Vocabulary Development Skills',
                'description' => 'Enhancing grammar and vocabulary skills.',
                'created_at' => now(),
                'updated_at' => now(),
                'subject_code' => '000',
            ],
            [
                'degree_programme_id' => 2,
                'name' => 'Advanced English-Speaking Skills & Listening Skills',
                'description' => 'Improving speaking and listening abilities.',
                'created_at' => now(),
                'updated_at' => now(),
                'subject_code' => '000',
            ],
            [
                'degree_programme_id' => 2,
                'name' => 'Advanced English Writing Skills & Reading Skills',
                'description' => 'Developing writing and reading proficiency.',
                'created_at' => now(),
                'updated_at' => now(),
                'subject_code' => '000',
            ],
            [
                'degree_programme_id' => 2,
                'name' => 'Basic French',
                'description' => 'Introduction to the French language.',
                'created_at' => now(),
                'updated_at' => now(),
                'subject_code' => '000',
            ],
            [
                'degree_programme_id' => 2,
                'name' => 'Basic Chinese',
                'description' => 'Introduction to the Chinese language.',
                'created_at' => now(),
                'updated_at' => now(),
                'subject_code' => '000',
            ],
            [
                'degree_programme_id' => 2,
                'name' => 'Database Management Systems I',
                'description' => 'Fundamentals of database management.',
                'created_at' => now(),
                'updated_at' => now(),
                'subject_code' => '000',
            ],
            [
                'degree_programme_id' => 2,
                'name' => 'System Analysis and Design',
                'description' => 'Analyzing and designing systems.',
                'created_at' => now(),
                'updated_at' => now(),
                'subject_code' => '000',
            ],
            [
                'degree_programme_id' => 2,
                'name' => 'Server Side Web Technologies',
                'description' => 'Web technologies for server-side development.',
                'created_at' => now(),
                'updated_at' => now(),
                'subject_code' => '000',
            ],
            [
                'degree_programme_id' => 2,
                'name' => 'Academic Essay Writing Skills',
                'description' => 'Skills for writing academic essays.',
                'created_at' => now(),
                'updated_at' => now(),
                'subject_code' => '000',
            ],
            [
                'degree_programme_id' => 2,
                'name' => 'Business Communication Skills',
                'description' => 'Effective communication in business contexts.',
                'created_at' => now(),
                'updated_at' => now(),
                'subject_code' => '000',
            ],
            [
                'degree_programme_id' => 2,
                'name' => 'Introduction to Presentation Skills',
                'description' => 'Basics of effective presentations.',
                'created_at' => now(),
                'updated_at' => now(),
                'subject_code' => '000',
            ],
            [
                'degree_programme_id' => 2,
                'name' => 'Techniques of Higher Education',
                'description' => 'Methods for success in higher education.',
                'created_at' => now(),
                'updated_at' => now(),
                'subject_code' => '000',
            ],
            [
                'degree_programme_id' => 2,
                'name' => 'Communicative Writing – I',
                'description' => 'Basics of effective written communication.',
                'created_at' => now(),
                'updated_at' => now(),
                'subject_code' => '000',
            ],
            [
                'degree_programme_id' => 2,
                'name' => 'Introduction to Computer Programming with Java',
                'description' => 'Introductory programming using Java.',
                'created_at' => now(),
                'updated_at' => now(),
                'subject_code' => '000',
            ],
            [
                'degree_programme_id' => 2,
                'name' => 'Intermediate French',
                'description' => 'Intermediate level French language skills.',
                'created_at' => now(),
                'updated_at' => now(),
                'subject_code' => '000',
            ],
            [
                'degree_programme_id' => 2,
                'name' => 'Intermediate Chinese',
                'description' => 'Intermediate level Chinese language skills.',
                'created_at' => now(),
                'updated_at' => now(),
                'subject_code' => '000',
            ],
            [
                'degree_programme_id' => 2,
                'name' => 'Computer Ethics and Basics of Law',
                'description' => 'Ethics and legal issues in computing.',
                'created_at' => now(),
                'updated_at' => now(),
                'subject_code' => '000',
            ],
            [
                'degree_programme_id' => 2,
                'name' => 'Communication Networks',
                'description' => 'Fundamentals of communication networks.',
                'created_at' => now(),
                'updated_at' => now(),
                'subject_code' => '000',
            ],
            [
                'degree_programme_id' => 2,
                'name' => 'Introduction to Object Oriented Programming Concepts',
                'description' => 'Basics of OOP concepts.',
                'created_at' => now(),
                'updated_at' => now(),
                'subject_code' => '000',
            ],
            [
                'degree_programme_id' => 2,
                'name' => 'Database Management Systems II',
                'description' => 'Advanced topics in database management.',
                'created_at' => now(),
                'updated_at' => now(),
                'subject_code' => '000',
            ],
            [
                'degree_programme_id' => 2,
                'name' => 'Mathematics for Computing II',
                'description' => 'Advanced mathematics for computing.',
                'created_at' => now(),
                'updated_at' => now(),
                'subject_code' => '000',
            ],
            [
                'degree_programme_id' => 2,
                'name' => 'Mobile Computing Technology',
                'description' => 'Introduction to mobile computing.',
                'created_at' => now(),
                'updated_at' => now(),
                'subject_code' => '000',
            ],
            [
                'degree_programme_id' => 2,
                'name' => 'Introduction to Public Speaking Skills',
                'description' => 'Fundamentals of public speaking.',
                'created_at' => now(),
                'updated_at' => now(),
                'subject_code' => '000',
            ],
            [
                'degree_programme_id' => 2,
                'name' => 'Communicative Writing II',
                'description' => 'Advanced writing communication skills.',
                'created_at' => now(),
                'updated_at' => now(),
                'subject_code' => '000',
            ],
            [
                'degree_programme_id' => 2,
                'name' => 'Analytical Reading',
                'description' => 'Skills for analytical reading.',
                'created_at' => now(),
                'updated_at' => now(),
                'subject_code' => '000',
            ],
            [
                'degree_programme_id' => 2,
                'name' => 'Introduction to English Literature Study Skills',
                'description' => 'Skills for studying English literature.',
                'created_at' => now(),
                'updated_at' => now(),
                'subject_code' => '000',
            ],
            [
                'degree_programme_id' => 2,
                'name' => 'Scientific Research Methodology',
                'description' => 'Methods for conducting scientific research.',
                'created_at' => now(),
                'updated_at' => now(),
                'subject_code' => '000',
            ],
            [
                'degree_programme_id' => 2,
                'name' => 'Information Security',
                'description' => 'Basics of information security.',
                'created_at' => now(),
                'updated_at' => now(),
                'subject_code' => '000',
            ],
            [
                'degree_programme_id' => 2,
                'name' => 'Software Engineering Principles',
                'description' => 'Fundamentals of software engineering.',
                'created_at' => now(),
                'updated_at' => now(),
                'subject_code' => '000',
            ],
            [
                'degree_programme_id' => 2,
                'name' => 'Human-Computer Interaction',
                'description' => 'Study of user interaction with computers.',
                'created_at' => now(),
                'updated_at' => now(),
                'subject_code' => '000',
            ],
            [
                'degree_programme_id' => 2,
                'name' => 'Project Management',
                'description' => 'Basics of managing projects.',
                'created_at' => now(),
                'updated_at' => now(),
                'subject_code' => '000',
            ],
            [
                'degree_programme_id' => 2,
                'name' => 'Advanced English for Academic Purposes',
                'description' => 'Advanced English for academic settings.',
                'created_at' => now(),
                'updated_at' => now(),
                'subject_code' => '000',
            ],
            [
                'degree_programme_id' => 2,
                'name' => 'Research Project',
                'description' => 'Conducting a research project.',
                'created_at' => now(),
                'updated_at' => now(),
                'subject_code' => '000',
            ],
            [
                'degree_programme_id' => 2,
                'name' => 'Introduction to Machine Learning',
                'description' => 'Basics of machine learning concepts.',
                'created_at' => now(),
                'updated_at' => now(),
                'subject_code' => '000',
            ],
            [
                'degree_programme_id' => 2,
                'name' => 'Data Science Fundamentals',
                'description' => 'Introduction to data science techniques.',
                'created_at' => now(),
                'updated_at' => now(),
                'subject_code' => '000',
            ],
            [
                'degree_programme_id' => 5,
                'name' => 'Buddhist Studies',
                'description' => 'Comprehensive study of Buddhist teachings.',
                'created_at' => now(),
                'updated_at' => now(),
                'subject_code' => '000',
            ],
            [
                'degree_programme_id' => 5,
                'name' => 'Leadership Principles',
                'description' => 'In-depth exploration of leadership theories and principles.',
                'created_at' => now(),
                'updated_at' => now(),
                'subject_code' => '000',
            ],
            [
                'degree_programme_id' => 5,
                'name' => 'Buddhist Ethics',
                'description' => 'Study of Buddhist ethical principles and moral conduct.',
                'created_at' => now(),
                'updated_at' => now(),
                'subject_code' => '000',
            ],
            [
                'degree_programme_id' => 5,
                'name' => 'Interfaith Dialogue',
                'description' => 'Understanding different religious perspectives and approaches to spirituality.',
                'created_at' => now(),
                'updated_at' => now(),
                'subject_code' => '000',
            ],
            [
                'degree_programme_id' => 5,
                'name' => 'Community Engagement',
                'description' => 'Learning to work with and support diverse Buddhist communities.',
                'created_at' => now(),
                'updated_at' => now(),
                'subject_code' => '000',
            ],
            [
                'degree_programme_id' => 5,
                'name' => 'Conflict Resolution',
                'description' => 'Techniques for managing and resolving conflicts within a Buddhist context.',
                'created_at' => now(),
                'updated_at' => now(),
                'subject_code' => '000',
            ],
            [
                'degree_programme_id' => 5,
                'name' => 'Meditation and Mindfulness and Yoga Practice',
                'description' => 'An introduction to meditation and mindfulness practices and Yoga.',
                'created_at' => now(),
                'updated_at' => now(),
                'subject_code' => '000',
            ],
            [
                'degree_programme_id' => 6,
                'name' => 'Pali Language',
                'description' => 'Extensive study of the Pali language, including reading, writing, grammar, and comprehension.',
                'created_at' => now(),
                'updated_at' => now(),
                'subject_code' => '000',
            ],
            [
                'degree_programme_id' => 6,
                'name' => 'Buddhist Doctrines',
                'description' => 'A comprehensive study of Buddhist teachings.',
                'created_at' => now(),
                'updated_at' => now(),
                'subject_code' => '000',
            ],
            [
                'degree_programme_id' => 6,
                'name' => 'Buddhist Scriptures',
                'description' => 'In-depth analysis and interpretation of key Pali Canon texts.',
                'created_at' => now(),
                'updated_at' => now(),
                'subject_code' => '000',
            ],
            [
                'degree_programme_id' => 6,
                'name' => 'Research Methodology',
                'description' => 'Development of research skills to critically analyze, translate, and interpret Pali texts.',
                'created_at' => now(),
                'updated_at' => now(),
                'subject_code' => '000',
            ],
        ];



        foreach ($subjects as $subject) {
            Subject::create($subject);
        }
    }
}
